# ===GENERAL PARAMETERS===
# 1. The name of the project will be used to separate the runs.
ProjName: dummy_test
# 2. Path to the directory containing the sample fastqs.
SamplePath: ../../../data/dummy/dummy_fq
# 3. Path to the sample sheet.
Samplesheet: ../../../data/dummy/metadata.csv
# 4. Indexed reference path.
RefPath: ../../../../frags/data/reference_genomes/hg38_bwa_reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
# 5. Output path.
OutPath: ../../../dummy
# 6. Path to TMPDIR.
TmpDir: ../../../dummy_tmp
# 7. Number of threads to use.
ThreadNr: 8
# Choose which trimmer to use. Can be [bbduk, cutadapt, none].
#Chosing none will turn trimming off.
Trimmer: bbduk
# Choose the contigs you want to run your analysis on.
# These names need to be the same as the contigs in the reference.
# Contigs: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y
# use if want UCSC chromosome naming for hg38
Contigs: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22

# ===TRIMMING PARAMETERS===
BbdukFlags: "ktrim=r k=23 mink=11 hdist=1"
#Path to the adapters used for trimming with Bbduk.
Adapters: ../../../resources/Bbduk/adapters.fa


#===FILTERING PARAMETERS===
# Read filtering - quality
FiltQual: 5

#===FREIA | EXTRACT_FRAGMENT_ENDS PARAMETERS===
# The number of bases to be extracted on the fragment ends.
nBase: 3

#===FREIA | DATA_TRANSFORMATION PARAMETERS===
# The fraction (between 0 and 1) of reads to use. The default is 1.
SubSampleRate: 1
# The size (in bases) of the minimum fragment size to analyze. The default is 1.
FragmSizeMin: 1
# The size (in bases) of the maximum fragment size to analyze. The default is 500.
FragmSizeMax: 500
# The number of bootstrapped samples to produce.
# This results in samples where the same read can be present multiple times!
BsSampNr: 0

#===FREIA | COMPARE_GROUPS PARAMETERS===
# Subset the trinucleotide ends to the firs n with highest proportions.
# If set to 0 all 64 trinucleotide end proportions will be present in the output.
SubsetResults: 0
# The path to the regrouping sheet. If empty will use the original samplesheet.
Regroup:

#===FREIA | FREIA SCORE PARAMETERS===
# 8. Path to the metadata file. The following columns are obligatory:
# sample_name, phenotype
MetaPath:  ../../../data/dummy/metadata.csv
# 9. To perform batch correction type the name of the column containing
# the batch IDs in the metadata file. Default: None
BatchIDs: None
# 10. Path to the panel of medians.
# A preset panel of medians is provided in rhe resources directory.
# To create you own panel of medians please use the Create_panels.py tool provided with FrEIA.
PanelMed: ../../../resources/FrEIA/panel_medians.csv
# 11. The name of control and case samples in the metadata file.
CtrName: control*
CasName: cancer
# 12. List of trinucleotides used to compute the FrEIA score.
TncCtr: ACA,ACC,ACT,CAC,CAT,CCA,CCC,CCT,CGA,CGC,CGT,CTT,GAC,GGC,TCT,AAG,ACG,AGA,AGG,ATA,ATG,CCG,GAG,GCG,GGG,GTA,GTG,TCG,TTA,TTC,TTG
TncCas: AAG,ACG,AGA,AGG,ATA,ATG,CCG,GAG,GCG,GGG,GTA,GTG,TCG,TTA,TTC,TTG,ACA,ACC,ACT,CAC,CAT,CCA,CCC,CCT,CGA,CGC,CGT,CTT,GAC,GGC,TCT
